# Generated by Django 2.2 on 2019-04-13 12:45

from django.db import migrations, models
import unixtimestampfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bandwidth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(default='device_id', max_length=256)),
                ('bytes_ts', models.IntegerField(default=None)),
                ('bytes_fs', models.IntegerField(default=None)),
                ('timestamp', unixtimestampfield.fields.UnixTimeStampField(default=None)),
            ],
        ),
    ]
