# Generated by Django 2.2 on 2019-04-13 12:48

from django.db import migrations
from main.bandwidths import BANDWIDTHS

# forward function
def add_bandwidth(apps, schema_editor):
    Bandwidth = apps.get_model('main','Bandwidth')
    
    for band in BANDWIDTHS:
        print(band)
        # print()
        b = Bandwidth.objects.get_or_create(
            device_id = band['device_id'],
            bytes_ts = band['bytes_ts'],
            bytes_fs = band['bytes_fs'],
            timestamp = band['timestamp'],
        )
        print(b)

# backward function
def remove_bandwidth(apps, schema_editor):
    Bandwidth = apps.get_model('main', 'Bandwidth')
 
    for band in BANDWIDTHS:
        b = Bandwidth.objects.get(
            device_id=band['device_id'],
        )
 
        b.delete()  

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            add_bandwidth,
            remove_bandwidth
        )        
    ]
